version: 2

models:
  - name: dim_customers
    columns:
      - name: customer_id
        tests: [not_null, unique]

  - name: dim_products
    columns:
      - name: product_id
        tests: [not_null, unique]

  - name: fact_orders
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: customer_id
        tests: [not_null]

  - name: fact_order_items
    columns:
      - name: order_id
        tests: [not_null]
      - name: order_item_id
        tests: [not_null]

